"""add cost and prompt_id to telemetry

Revision ID: de9c1517c9c5
Revises: 7e070742e983
Create Date: 2025-12-04 23:05:04.621974

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de9c1517c9c5"
down_revision: str | Sequence[str] | None = "7e070742e983"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telemetry", sa.Column("cost", sa.Float(), nullable=True))
    op.add_column(
        "telemetry",
        sa.Column(
            "prompt_id",
            sa.Integer(),
            nullable=True))
    op.create_foreign_key(
        "fk_telemetry_prompt_id", "telemetry", "prompt", ["prompt_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_telemetry_prompt_id",
        "telemetry",
        type_="foreignkey")
    op.drop_column("telemetry", "prompt_id")
    op.drop_column("telemetry", "cost")
    # ### end Alembic commands ###
